# Generated by Django 5.1.4 on 2025-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='bio',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.IntegerField(max_length=15, unique=True),
        ),
    ]
