# Generated by Django 5.1.4 on 2025-02-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mahasiswa_bio_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.IntegerField(unique=True),
        ),
    ]
