# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\itsma\OneDrive\Documents\Project\Belajar\Python\App\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("220x180")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 180,
    width = 220,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)


canvas.place(x = 0, y = 0)


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))

image_1 = canvas.create_image(
    110.0,
    90.0,
    image=image_image_1
)


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))

image_2 = canvas.create_image(
    110.0,
    62.0,
    image=image_image_2
)

# Create a text item on the canvas after image_2
text_item = canvas.create_text(
    110.0, 62.0,  # Position it over image_2
    text="",  # Initially empty
    fill="black",  # Text color
    font=("Arial", 12)  # Font and size
)

def on_button_1_click():
    canvas.itemconfig(text_item, text="HELLLLLLLLLO")

button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=on_button_1_click,  # Update command to call the new function
    relief="flat"
)
button_1.place(
    x=74.0,
    y=135.0,
    width=73.0,
    height=20.0
)

window.resizable(False, False)
window.mainloop()
